#!/usr/bin/env python3
"""
Create a .venv and install the full project inside it.

Usage:
    python3 install.py            # first run: generates requirements.lock, then installs
                                  # subsequent runs: installs straight from requirements.lock
    python3 install.py --lock     # regenerate requirements.lock (after changing pyproject.toml)
    python3 install.py --no-dev   # exclude dev extras (pytest, ruff, pip-tools)
    python3 install.py --check    # verify every import after install
    python3 install.py --force    # wipe .venv and reinstall from scratch

requirements.lock is generated by pip-compile (pip-tools) and should be committed to git
so that every collaborator gets the same pinned dependency tree without having to resolve it.
"""

import argparse
import shutil
import subprocess
import sys
import venv
from pathlib import Path

MIN_PYTHON = (3, 11)
ROOT = Path(__file__).parent.resolve()
VENV_DIR = ROOT / ".venv"
LOCK_FILE = ROOT / "requirements.lock"


def abort(msg: str) -> None:
    print(f"\n  ERROR: {msg}", file=sys.stderr)
    sys.exit(1)


def run(cmd: list[str], **kwargs) -> subprocess.CompletedProcess:
    print(f"  $ {' '.join(str(c) for c in cmd)}")
    result = subprocess.run(cmd, **kwargs)
    if result.returncode != 0:
        abort(f"Command failed (exit {result.returncode})")
    return result


def python_in_venv() -> Path:
    if sys.platform == "win32":
        return VENV_DIR / "Scripts" / "python.exe"
    return VENV_DIR / "bin" / "python"


def pip_in_venv() -> list[str]:
    return [str(python_in_venv()), "-m", "pip"]


# ── pre-flight ────────────────────────────────────────────────────────────────

def check_python_version() -> None:
    if sys.version_info < MIN_PYTHON:
        abort(
            f"Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]}+ required, "
            f"got {sys.version_info.major}.{sys.version_info.minor}"
        )
    print(f"  Python {sys.version.split()[0]} — OK")


def check_system_deps() -> None:
    missing = [t for t in ("git",) if shutil.which(t) is None]
    if missing:
        abort(f"Missing system tools: {', '.join(missing)}")


# ── venv ──────────────────────────────────────────────────────────────────────

def create_venv(force: bool = False) -> None:
    if force and VENV_DIR.exists():
        print(f"  --force: removing existing .venv at {VENV_DIR} …")
        shutil.rmtree(VENV_DIR)
        print("  Removed.")
    if VENV_DIR.exists():
        print(f"  .venv already exists at {VENV_DIR} — reusing")
    else:
        print(f"  Creating virtual environment at {VENV_DIR} …")
        venv.create(str(VENV_DIR), with_pip=True, clear=False, symlinks=True)
        print("  Done.")


# ── lock file ─────────────────────────────────────────────────────────────────

def generate_lock(include_dev: bool) -> None:
    print(f"\n  {'Regenerating' if LOCK_FILE.exists() else 'Generating'} {LOCK_FILE.name} via pip-compile …")
    run(pip_in_venv() + ["install", "--upgrade", "pip-tools"])
    extras = ["--extra", "full"]
    if include_dev:
        extras += ["--extra", "dev"]
    run(
        [str(python_in_venv()), "-m", "piptools", "compile",
         "pyproject.toml",
         *extras,
         "--output-file", str(LOCK_FILE),
         "--resolver", "backtracking",
         "--annotate",
         "--strip-extras",
        ]
    )
    print(f"\n  {LOCK_FILE.name} written.")
    print("  Commit this file so collaborators get the same pinned tree.\n")


# ── install ───────────────────────────────────────────────────────────────────

def upgrade_pip() -> None:
    run(pip_in_venv() + ["install", "--upgrade", "pip", "setuptools", "wheel"])


def install_from_lock() -> None:
    print(f"  Installing pinned deps from {LOCK_FILE.name} …")
    run(pip_in_venv() + ["install", "-r", str(LOCK_FILE)])
    run(pip_in_venv() + ["install", "-e", ".", "--no-deps", "--no-warn-script-location"])


# ── verification ──────────────────────────────────────────────────────────────

VERIFY_IMPORTS = [
    # core
    "pandas", "numpy", "scipy", "sklearn", "pydantic", "yaml",
    "openpyxl", "statsmodels", "plotly", "matplotlib",
    # full extras
    "torch", "neuroHarmonize", "neuroCombat", "nibabel", "kaleido",
    # notebook utilities
    "IPython", "nbformat",
    # the package itself
    "trans_diag",
]


def verify_install() -> None:
    print("\n  Verifying imports …")
    py = str(python_in_venv())
    failed = []
    for pkg in VERIFY_IMPORTS:
        result = subprocess.run([py, "-c", f"import {pkg}"], capture_output=True)
        ok = result.returncode == 0
        print(f"    {'✓' if ok else '✗'}  {pkg:<25} {'OK' if ok else 'MISSING'}")
        if not ok:
            failed.append(pkg)
    if failed:
        print(f"\n  WARNING: {len(failed)} package(s) failed to import: {', '.join(failed)}")
        print("  Some optional deps (e.g. neuroHarmonize, kaleido) may have system-level requirements.")
    else:
        print("\n  All imports OK.")


# ── activation hint ───────────────────────────────────────────────────────────

def print_activation_hint() -> None:
    activate = r".venv\Scripts\activate" if sys.platform == "win32" else "source .venv/bin/activate"
    print(f"""
  ─────────────────────────────────────────────────────────────────
  Installation complete.

  Activate the environment:
      {activate}

  Then run the pipeline:
      python scripts/00_run_all.py      # full manuscript pipeline
      python -m pytest tests/ -q        # 76 unit + golden-number tests
      python scripts/verify.py          # harmonization smoke test

  Or use the venv Python directly without activating:
      .venv/bin/python scripts/00_run_all.py

  To update pinned deps after editing pyproject.toml:
      python3 install.py --lock
  ─────────────────────────────────────────────────────────────────
""")


# ── main ──────────────────────────────────────────────────────────────────────

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--lock",   action="store_true", help="Regenerate requirements.lock (after editing pyproject.toml)")
    parser.add_argument("--no-dev", action="store_true", help="Exclude dev extras (pytest, ruff, pip-tools)")
    parser.add_argument("--check",  action="store_true", help="Verify every import after install")
    parser.add_argument("--force",  action="store_true", help="Wipe existing .venv and reinstall from scratch")
    args = parser.parse_args()

    print("\n  FACE trans-diagnostic phenotypes — environment setup")
    print(f"  Project root: {ROOT}\n")

    check_python_version()
    check_system_deps()
    create_venv(force=args.force)
    upgrade_pip()

    # generate lock file if it doesn't exist yet, or if --lock/--force was passed
    if not LOCK_FILE.exists() or args.lock or args.force:
        generate_lock(include_dev=not args.no_dev)

    install_from_lock()

    if args.check:
        verify_install()

    print_activation_hint()


if __name__ == "__main__":
    main()
