$schema_version: 1
labs:
- csv_col: gluc
  name: Glucose
  name_fr: Glycemie a jeun
  unit: mmol/L
  normal_range:
  - 3.9
  - 5.5
- csv_col: hba1c
  name: HbA1c
  name_fr: Hemoglobine glyquee
  unit: '%'
  normal_range:
  - 4.0
  - 5.6
- csv_col: chol
  name: Total cholesterol
  name_fr: Cholesterol total
  unit: mmol/L
  normal_range:
  - 0.0
  - 5.2
- csv_col: hdl
  name: HDL
  name_fr: HDL-cholesterol
  unit: mmol/L
  normal_range:
  - 1.0
  - 99.0
- csv_col: ldl
  name: LDL
  name_fr: LDL-cholesterol
  unit: mmol/L
  normal_range:
  - 0.0
  - 3.4
- csv_col: trig
  name: Triglycerides
  name_fr: Triglycerides
  unit: mmol/L
  normal_range:
  - 0.0
  - 1.7
- csv_col: tsh
  name: TSH
  name_fr: TSH
  unit: mUI/L
  normal_range:
  - 0.4
  - 4.0
- csv_col: t3l
  name: Free T3
  name_fr: T3 libre
  unit: pmol/L
  normal_range:
  - 3.1
  - 6.8
- csv_col: t4l
  name: Free T4
  name_fr: T4 libre
  unit: pmol/L
  normal_range:
  - 12.0
  - 22.0
- csv_col: creat
  name: Creatinine
  name_fr: Creatinine
  unit: umol/L
  normal_range:
  - 60.0
  - 110.0
  sex_specific: true
- csv_col: uree
  name: Urea
  name_fr: Uree
  unit: mmol/L
  normal_range:
  - 2.5
  - 7.5
- csv_col: urate
  name: Urate
  name_fr: Uricemie
  unit: umol/L
  normal_range:
  - 150.0
  - 420.0
- csv_col: alat
  name: ALT
  name_fr: ALAT
  unit: UI/L
  normal_range:
  - 5.0
  - 40.0
- csv_col: asat
  name: AST
  name_fr: ASAT
  unit: UI/L
  normal_range:
  - 5.0
  - 40.0
- csv_col: ggt
  name: GGT
  name_fr: Gamma-GT
  unit: UI/L
  normal_range:
  - 5.0
  - 60.0
- csv_col: pal
  name: ALP
  name_fr: Phosphatases alcalines
  unit: UI/L
  normal_range:
  - 40.0
  - 130.0
- csv_col: biltot
  name: Total bilirubin
  name_fr: Bilirubine totale
  unit: umol/L
  normal_range:
  - 3.0
  - 21.0
- csv_col: alb
  name: Albumin
  name_fr: Albumine
  unit: g/L
  normal_range:
  - 35.0
  - 50.0
- csv_col: prot
  name: Total protein
  name_fr: Proteines totales
  unit: g/L
  normal_range:
  - 65.0
  - 80.0
- csv_col: crp
  name: CRP
  name_fr: Proteine C reactive
  unit: mg/L
  normal_range:
  - 0.0
  - 5.0
- csv_col: prolctn
  name: Prolactin
  name_fr: Prolactine
  unit: ng/mL
  normal_range:
  - 2.0
  - 25.0
- csv_col: cortisol
  name: Cortisol
  name_fr: Cortisolemie
  unit: nmol/L
  normal_range:
  - 170.0
  - 540.0
- csv_col: vitd
  name: Vitamin D
  name_fr: Vitamine D
  unit: nmol/L
  normal_range:
  - 50.0
  - 125.0
- csv_col: vitb12
  name: Vitamin B12
  name_fr: Vitamine B12
  unit: pmol/L
  normal_range:
  - 148.0
  - 590.0
- csv_col: folate
  name: Folate
  name_fr: Folates
  unit: nmol/L
  normal_range:
  - 7.0
  - 45.0
- csv_col: fer
  name: Iron
  name_fr: Fer serique
  unit: umol/L
  normal_range:
  - 9.0
  - 30.0
- csv_col: ferritn
  name: Ferritin
  name_fr: Ferritine
  unit: ug/L
  normal_range:
  - 15.0
  - 300.0
- csv_col: calcium
  name: Calcium
  name_fr: Calcemie
  unit: mmol/L
  normal_range:
  - 2.15
  - 2.55
- csv_col: phosph
  name: Phosphate
  name_fr: Phosphoremie
  unit: mmol/L
  normal_range:
  - 0.8
  - 1.5
- csv_col: sodium
  name: Sodium
  name_fr: Natremie
  unit: mmol/L
  normal_range:
  - 136.0
  - 145.0
- csv_col: k
  name: Potassium
  name_fr: Kaliemie
  unit: mmol/L
  normal_range:
  - 3.5
  - 5.0
- csv_col: chlore
  name: Chloride
  name_fr: Chloremie
  unit: mmol/L
  normal_range:
  - 98.0
  - 106.0
- csv_col: bicarb
  name: Bicarbonate
  name_fr: Bicarbonates
  unit: mmol/L
  normal_range:
  - 22.0
  - 29.0
- csv_col: hgb
  name: Hemoglobin
  name_fr: Hemoglobine
  unit: g/dL
  normal_range:
  - 12.0
  - 17.0
  sex_specific: true
- csv_col: hct
  name: Hematocrit
  name_fr: Hematocrite
  unit: '%'
  normal_range:
  - 36.0
  - 50.0
- csv_col: wbc
  name: WBC
  name_fr: Leucocytes
  unit: G/L
  normal_range:
  - 4.0
  - 10.0
- csv_col: plat
  name: Platelets
  name_fr: Plaquettes
  unit: G/L
  normal_range:
  - 150.0
  - 400.0
- csv_col: rbc
  name: RBC
  name_fr: Erythrocytes
  unit: T/L
  normal_range:
  - 3.8
  - 5.5
- csv_col: vgm
  name: MCV
  name_fr: VGM
  unit: fL
  normal_range:
  - 80.0
  - 100.0
- csv_col: tcmh
  name: MCH
  name_fr: TCMH
  unit: pg
  normal_range:
  - 27.0
  - 33.0
- csv_col: ccmh
  name: MCHC
  name_fr: CCMH
  unit: g/dL
  normal_range:
  - 31.0
  - 36.0
- csv_col: neutro
  name: Neutrophils
  name_fr: Polynucleaires neutrophiles
  unit: G/L
  normal_range:
  - 1.5
  - 7.5
- csv_col: lympho
  name: Lymphocytes
  name_fr: Lymphocytes
  unit: G/L
  normal_range:
  - 1.0
  - 4.0
- csv_col: mono
  name: Monocytes
  name_fr: Monocytes
  unit: G/L
  normal_range:
  - 0.2
  - 1.0
- csv_col: eosino
  name: Eosinophils
  name_fr: Polynucleaires eosinophiles
  unit: G/L
  normal_range:
  - 0.0
  - 0.5
