$schema_version: 1
labs:
- csv_col: gluc
  name: Glucose
  name_fr: Glycémie à jeun
  unit: mmol/L
  normal_range:
  - 3.9
  - 5.5
- csv_col: hba1c
  name: HbA1c
  name_fr: Hémoglobine glyquée
  unit: '%'
  normal_range:
  - 4.0
  - 5.6
- csv_col: chol
  name: Total cholesterol
  name_fr: Cholestérol total
  unit: mmol/L
  normal_range:
  - 0.0
  - 5.2
- csv_col: hdl
  name: HDL
  name_fr: HDL-cholestérol
  unit: mmol/L
  normal_range:
  - 1.0
  - 99.0
- csv_col: ldl
  name: LDL
  name_fr: LDL-cholestérol
  unit: mmol/L
  normal_range:
  - 0.0
  - 3.4
- csv_col: trig
  name: Triglycerides
  name_fr: Triglycérides
  unit: mmol/L
  normal_range:
  - 0.0
  - 1.7
- csv_col: tsh
  name: TSH
  name_fr: TSH
  unit: mUI/L
  normal_range:
  - 0.4
  - 4.0
- csv_col: creat
  name: Creatinine
  name_fr: Créatinine
  unit: µmol/L
  normal_range:
  - 60.0
  - 110.0
  sex_specific: true
- csv_col: egf
  name: eGFR
  name_fr: DFG estimé
  unit: mL/min
  normal_range:
  - 90.0
  - 999.0
- csv_col: prolctn
  name: Prolactin
  name_fr: Prolactine
  unit: ng/mL
  normal_range:
  - 2.0
  - 25.0
- csv_col: crp
  name: CRP
  name_fr: Protéine C réactive
  unit: mg/L
  normal_range:
  - 0.0
  - 5.0
- csv_col: hgb
  name: Hemoglobin
  name_fr: Hémoglobine
  unit: g/dL
  normal_range:
  - 12.0
  - 17.0
  sex_specific: true
- csv_col: wbc
  name: WBC
  name_fr: Leucocytes
  unit: G/L
  normal_range:
  - 4.0
  - 10.0
- csv_col: plat
  name: Platelets
  name_fr: Plaquettes
  unit: G/L
  normal_range:
  - 150.0
  - 400.0
- csv_col: urate
  name: Uric acid
  name_fr: Acide urique
  unit: µmol/L
  normal_range:
  - 150.0
  - 420.0
  sex_specific: true
