#!/usr/bin/env python3
"""Generate ``requirements.lock`` by pinning the EXACT installed versions of the project's dependency
closure (issue P7-01).

The previous lock was stale and wrong: autogenerated for a foreign path under Python 3.12, it pinned
deleted V2 dependencies (``torch``/``neurocombat``/``nibabel`` via ``trans-diag``) and — critically —
EXCLUDED the entire Bayesian backend (``pymc``/``pytensor``/``numpyro``/``jax``/``arviz``), which every
certified result depends on. We pin the actually-installed closure (no network; faithful to the tested
environment that produced the results) rather than re-resolving against PyPI, because the backend
versions here are pinned-by-environment and a fresh resolve could pull incompatible ones.

    python3 scripts/gen_lockfile.py        # rewrites requirements.lock; run after changing deps
"""
from __future__ import annotations

import importlib.metadata as md
import platform
import sys
from pathlib import Path

from packaging.requirements import Requirement

REPO = Path(__file__).resolve().parents[1]

# pyproject [project.dependencies] + every optional-dependencies group (figures/dev/bayesian/full).
ROOTS = [
    "pandas", "numpy", "scipy", "scikit-learn", "pydantic", "pyyaml", "openpyxl", "statsmodels",
    "factor_analyzer", "plotly", "matplotlib", "pyarrow",                # core
    "kaleido",                                                           # figures / full
    "pytest", "pytest-cov", "ruff", "pip-tools",                        # dev
    "pymc", "arviz", "h5netcdf", "numpyro", "jax",                      # bayesian
]


def _norm(name: str) -> str:
    return name.lower().replace("_", "-")


def closure() -> dict[str, str | None]:
    seen: dict[str, str | None] = {}

    def walk(name: str) -> None:
        try:
            dist = md.distribution(name)
        except md.PackageNotFoundError:
            seen.setdefault(_norm(name), None)
            return
        key = _norm(dist.metadata["Name"])
        if key in seen and seen[key] is not None:
            return
        seen[key] = dist.version
        for spec in (md.requires(name) or []):
            try:
                req = Requirement(spec)
            except Exception:
                continue
            # Follow base deps only (skip extra-only / platform-excluded transitive deps).
            if req.marker is not None and not req.marker.evaluate({"extra": ""}):
                continue
            walk(req.name)

    for r in ROOTS:
        walk(r)
    return seen


def main() -> None:
    pins = closure()
    header = [
        "# requirements.lock — EXACT pins of the FACE dependency closure.",
        "# Generated by scripts/gen_lockfile.py from the tested environment (no network; faithful to",
        "# what produced the certified results). Regenerate after changing dependencies.",
        f"# Python {sys.version.split()[0]} · {platform.system()} {platform.machine()}",
        "# Bayesian backend IS included (pymc/pytensor/numpyro/jax/jaxlib/arviz/h5netcdf).",
        "",
    ]
    body = [f"{name}=={ver}" for name, ver in sorted(pins.items()) if ver]
    (REPO / "requirements.lock").write_text("\n".join(header + body) + "\n")
    print(f"wrote requirements.lock — {len(body)} pinned packages")
    for key in ["pymc", "pytensor", "numpyro", "jax", "jaxlib", "arviz", "h5netcdf"]:
        print(f"  {key}=={pins.get(key)}")
    missing = [k for k, v in pins.items() if v is None]
    if missing:
        print(f"  (declared-but-not-installed: {missing})")


if __name__ == "__main__":
    main()
